import type { DifficultyDef, DifficultyId, LevelDef, LevelId } from './types'

/**
 * Each level is a distinct sport in a distinct place. The physics blocks are
 * hand-tuned so they feel different in the hand: a boat slides and drifts,
 * a go-kart is twitchy and grippy, a surfboard rides the sway of the wave.
 */
export const LEVELS: LevelDef[] = [
  {
    id: 'snowboard',
    name: 'Snowboard',
    location: 'Niseko, Japan',
    tagline: 'Powder day. Point it downhill.',
    glyph: '🏂',
    flag: '🇯🇵',
    surface: 'slope',
    musicKey: 0,
    length: 2600,
    roadWidth: 2000,
    curviness: 0.55,
    hilliness: 0.7,
    rampRate: 1,
    water: false,
    palette: {
      skyTop: '#1d3f7a',
      skyBottom: '#8fc4f0',
      sun: '#fff6e0',
      sunGlow: 'rgba(255,240,200,0.55)',
      ridgeFar: '#5f7fae',
      ridgeNear: '#3d5a86',
      // The verges are deliberately much bluer than the piste: on a white-on-
      // white mountain the run has to stay obvious to a five-year-old.
      groundA: '#9dc3e6',
      groundB: '#93bade',
      laneA: '#ffffff',
      laneB: '#f4f9ff',
      rumbleA: '#3f7fc4',
      rumbleB: '#e8f3ff',
      centerLine: null,
      fog: '#bcd8f2',
      accent: '#5ec8ff',
      spray: '#ffffff',
    },
    physics: {
      topSpeed: 9400,
      accel: 3400,
      offSurfaceDrag: 5200,
      steerRate: 5.4,
      grip: 6.5,
      centrifugal: 0.42,
      jumpImpulse: 1180,
      gravity: 3000,
      bob: 0.15,
      lean: 0.5,
    },
    scenery: ['pine', 'pine', 'rock', 'flag'],
    obstacles: ['rock', 'tree', 'log'],
  },
  {
    id: 'skateboard',
    name: 'Skateboard',
    location: 'San Francisco, USA',
    tagline: 'Bomb the hill. Mind the traffic.',
    glyph: '🛹',
    flag: '🇺🇸',
    surface: 'street',
    musicKey: 3,
    length: 2400,
    roadWidth: 1850,
    curviness: 0.45,
    hilliness: 0.95,
    rampRate: 0.9,
    water: false,
    palette: {
      skyTop: '#2b1f52',
      skyBottom: '#ff9e6d',
      sun: '#fff1c9',
      sunGlow: 'rgba(255,160,110,0.5)',
      ridgeFar: '#6b5487',
      ridgeNear: '#3f3160',
      groundA: '#4b4a52',
      groundB: '#43424a',
      laneA: '#5c5b64',
      laneB: '#55545d',
      rumbleA: '#e8e2d4',
      rumbleB: '#3a393f',
      centerLine: '#f2d16b',
      fog: '#b58a86',
      accent: '#ff8a4c',
      spray: '#d9d2c4',
    },
    physics: {
      topSpeed: 8800,
      accel: 3000,
      offSurfaceDrag: 6400,
      steerRate: 6.2,
      grip: 8.5,
      centrifugal: 0.3,
      jumpImpulse: 1020,
      gravity: 3200,
      bob: 0.05,
      lean: 0.42,
    },
    scenery: ['building', 'streetlight', 'building', 'building'],
    obstacles: ['cone', 'car', 'hydrant', 'crate'],
  },
  {
    id: 'rollerblade',
    name: 'Rollerblades',
    location: 'Barcelona, Spain',
    tagline: 'Seaside promenade, full send.',
    glyph: '🛼',
    flag: '🇪🇸',
    surface: 'promenade',
    musicKey: 5,
    length: 2200,
    roadWidth: 1750,
    curviness: 0.6,
    hilliness: 0.45,
    rampRate: 0.85,
    water: false,
    palette: {
      skyTop: '#0f6ab5',
      skyBottom: '#8fdcf5',
      sun: '#fffbe6',
      sunGlow: 'rgba(255,246,200,0.5)',
      ridgeFar: '#57a8c9',
      ridgeNear: '#2f7fa6',
      groundA: '#e8c98f',
      groundB: '#dfbe80',
      laneA: '#d8d3c6',
      laneB: '#d0cabd',
      rumbleA: '#c25b4a',
      rumbleB: '#f0ece2',
      centerLine: '#ffffff',
      fog: '#cfe3ec',
      accent: '#ff5f8d',
      spray: '#f5e6c8',
    },
    physics: {
      topSpeed: 8200,
      accel: 3100,
      offSurfaceDrag: 6800,
      steerRate: 7,
      grip: 9,
      centrifugal: 0.26,
      jumpImpulse: 900,
      gravity: 3300,
      bob: 0.08,
      lean: 0.36,
    },
    scenery: ['palm', 'palm', 'building', 'flag'],
    obstacles: ['cone', 'crate', 'hydrant'],
  },
  {
    id: 'gokart',
    name: 'Go-Kart',
    location: 'Monza, Italy',
    tagline: 'Tiny kart. Enormous confidence.',
    glyph: '🏎️',
    flag: '🇮🇹',
    surface: 'circuit',
    musicKey: 7,
    length: 2800,
    roadWidth: 2100,
    curviness: 0.8,
    hilliness: 0.35,
    rampRate: 0.6,
    water: false,
    palette: {
      skyTop: '#1a5fb4',
      skyBottom: '#a8d8f0',
      sun: '#ffffff',
      sunGlow: 'rgba(255,255,255,0.45)',
      ridgeFar: '#7fa05f',
      ridgeNear: '#547a3a',
      groundA: '#6faa4a',
      groundB: '#659e42',
      laneA: '#4a4a52',
      laneB: '#45454d',
      rumbleA: '#e03b3b',
      rumbleB: '#f5f5f5',
      centerLine: '#ffffff',
      fog: '#b9d6e8',
      accent: '#ffd23f',
      spray: '#8a8a8a',
    },
    physics: {
      topSpeed: 10200,
      accel: 4200,
      offSurfaceDrag: 8200,
      steerRate: 7.6,
      grip: 11,
      centrifugal: 0.5,
      jumpImpulse: 820,
      gravity: 3600,
      bob: 0.03,
      lean: 0.3,
    },
    scenery: ['flag', 'building', 'flag', 'rock'],
    obstacles: ['cone', 'barrel', 'car'],
  },
  {
    id: 'boat',
    name: 'Speedboat',
    location: 'Amazon River, Brazil',
    tagline: 'Downstream, wide open.',
    glyph: '🚤',
    flag: '🇧🇷',
    surface: 'river',
    musicKey: -2,
    length: 2500,
    roadWidth: 2200,
    curviness: 0.7,
    hilliness: 0.15,
    rampRate: 0.7,
    water: true,
    palette: {
      skyTop: '#0b6e63',
      skyBottom: '#bff0d8',
      sun: '#fffce8',
      sunGlow: 'rgba(230,255,210,0.5)',
      ridgeFar: '#2f7a55',
      ridgeNear: '#1d5940',
      groundA: '#2e6b45',
      groundB: '#27603d',
      laneA: '#2f8fa8',
      laneB: '#2a839c',
      rumbleA: '#a8d8b0',
      rumbleB: '#5fae8a',
      centerLine: null,
      fog: '#9fd6c8',
      accent: '#3fe0c0',
      spray: '#e8ffff',
    },
    physics: {
      topSpeed: 9000,
      accel: 2600,
      offSurfaceDrag: 4200,
      steerRate: 4.4,
      grip: 3.6,
      centrifugal: 0.34,
      jumpImpulse: 1050,
      gravity: 2700,
      bob: 0.55,
      lean: 0.55,
    },
    scenery: ['palm', 'reed', 'buoy', 'palm'],
    obstacles: ['log', 'rock', 'barrel', 'crate'],
  },
  {
    id: 'surf',
    name: 'Surfboard',
    location: 'Nazaré, Portugal',
    tagline: 'The wave is going down too.',
    glyph: '🏄',
    flag: '🇵🇹',
    surface: 'wave',
    musicKey: -4,
    length: 2300,
    roadWidth: 2050,
    curviness: 0.75,
    hilliness: 0.55,
    rampRate: 0.8,
    water: true,
    palette: {
      skyTop: '#12315e',
      skyBottom: '#f2b183',
      sun: '#ffe9b8',
      sunGlow: 'rgba(255,190,130,0.55)',
      ridgeFar: '#3c5f8a',
      ridgeNear: '#25406a',
      groundA: '#1d4f7a',
      groundB: '#194671',
      laneA: '#2f86c4',
      laneB: '#2a7cb8',
      rumbleA: '#ffffff',
      rumbleB: '#a8dcf5',
      centerLine: null,
      fog: '#8fb8d8',
      accent: '#ffb85c',
      spray: '#ffffff',
    },
    physics: {
      topSpeed: 8600,
      accel: 2400,
      offSurfaceDrag: 4600,
      steerRate: 4.8,
      grip: 4.2,
      centrifugal: 0.38,
      jumpImpulse: 1120,
      gravity: 2600,
      bob: 0.7,
      lean: 0.6,
    },
    scenery: ['buoy', 'rock', 'buoy', 'flag'],
    obstacles: ['rock', 'log', 'barrel'],
  },
  {
    id: 'car',
    name: 'Rally Car',
    location: 'Atlas Mountains, Morocco',
    tagline: 'Gravel, dust, and no brakes.',
    glyph: '🚗',
    flag: '🇲🇦',
    surface: 'pass',
    musicKey: 2,
    length: 3000,
    roadWidth: 1900,
    curviness: 0.85,
    hilliness: 0.8,
    rampRate: 0.75,
    water: false,
    palette: {
      skyTop: '#b8560f',
      skyBottom: '#ffd9a0',
      sun: '#fff4d6',
      sunGlow: 'rgba(255,200,120,0.55)',
      ridgeFar: '#a8724a',
      ridgeNear: '#7d4f2f',
      groundA: '#c9884f',
      groundB: '#bd7d46',
      laneA: '#9c6f45',
      laneB: '#956840',
      rumbleA: '#e8d0a8',
      rumbleB: '#7d5330',
      centerLine: null,
      fog: '#e0b483',
      accent: '#ff7a29',
      spray: '#e8c9a0',
    },
    physics: {
      topSpeed: 10600,
      accel: 3800,
      offSurfaceDrag: 7000,
      steerRate: 6.4,
      grip: 7,
      centrifugal: 0.55,
      jumpImpulse: 980,
      gravity: 3400,
      bob: 0.12,
      lean: 0.46,
    },
    scenery: ['cactus', 'rock', 'rock', 'cactus'],
    obstacles: ['rock', 'barrel', 'crate', 'car'],
  },
]

export const DIFFICULTIES: DifficultyDef[] = [
  {
    id: 'easy',
    name: 'Easy',
    blurb: 'Just steer left and right. You cannot lose.',
    glyph: '🌱',
    speedScale: 0.62,
    obstacleScale: 0.45,
    lives: 0,
    jumpEnabled: false,
    scoreScale: 1,
    assist: 0.55,
    minGap: 1100,
  },
  {
    id: 'medium',
    name: 'Medium',
    blurb: 'Faster, tighter, and you can jump. Three lives.',
    glyph: '🔥',
    speedScale: 0.85,
    obstacleScale: 0.85,
    lives: 3,
    jumpEnabled: true,
    scoreScale: 1.6,
    assist: 0.15,
    minGap: 780,
  },
  {
    id: 'hard',
    name: 'Hard',
    blurb: 'Full speed, packed course, two lives. Good luck.',
    glyph: '💀',
    speedScale: 1,
    obstacleScale: 1.3,
    lives: 2,
    jumpEnabled: true,
    scoreScale: 2.5,
    assist: 0,
    minGap: 560,
  },
]

export const getLevel = (id: LevelId): LevelDef => {
  const level = LEVELS.find((l) => l.id === id)
  if (!level) throw new Error(`Unknown level: ${id}`)
  return level
}

export const getDifficulty = (id: DifficultyId): DifficultyDef => {
  const difficulty = DIFFICULTIES.find((d) => d.id === id)
  if (!difficulty) throw new Error(`Unknown difficulty: ${id}`)
  return difficulty
}
